[[1823-01-21]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
Death of Gideon Olin, American politician (b. 1743)
"""

[[1823-01-21]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
Death of Cayetano José Rodríguez, Argentine representative to the Congress of Tucumán
"""

[[1823-01-21]]
lang = "fr"
citation = "https://fr.wikipedia.org/wiki/1823"
text = """
Décès de Gianni Felice, graveur et un peintre italien (° 15 décembre 1758).
"""

[[1823-01-22]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
Death of John Julius Angerstein, Russian-born English merchant, insurer and art collector (b. 1735)
"""

[[1823-01-22]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
By secret treaty signed at the Congress of Verona, the Quintuple Alliance gives France a mandate to invade
Spain for the purpose of restoring Ferdinand VII (who has been captured by armed revolutionary liberals) as absolute monarch of the country.
"""

[[1823-01-23]]
lang = "en"
text = """
In Paviland Cave on the Gower Peninsula of Wales, William Buckland inspects
the "Red Lady of Paviland",the first identification of a prehistoric (male) human burial.
"""
citation = "https://en.wikipedia.org/wiki/1823"

[[1823-02-03]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
kson Male Academy, precursor of Union University, opens in Tennessee.
Gioachino Rossini's opera Semiramide is first performed, at La Fenice in Venice.
"""

[[1823-02-10]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
The first worldwide carnival parade takes place in Cologne, Prussia.
"""

[[1823-02-11]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
Carnival tragedy of [1823: About 110 boys are killed during a stampede at the Convent of the Minori Osservanti in Valletta, Malta.
"""

[[1823-02-15]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
pprox.) – The first officially recognised gold is found in Australia, by surveyor James McBrien at Fish River, near Bathurst, New South Wales, predating the Australian gold rushes.[
    """

[[1823-02-17]]
lang = "fr"
citation = "https://fr.wikipedia.org/wiki/1823"
text = """
arrivée à Kouka, résidence du maï du Bornou, d’une expédition britannique, qui explore le Sud du Sahara. Denham et Clapperton, porteurs de recommandations diplomatiques, quittent Tripoli (1822), traversent le Sahara, puis atteignent le lac Tchad. Il séjournent dans l’empire du Bornou et visitent les pays voisins
"""

[[1823-02-20]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
Explorer James Weddell's expedition to Antarctica reaches latitude 74°15' S and longitude 34°16'45 W: the southernmost position any ship has reached at this time, a record that will hold until 1841.[
    """

[[1823-03-15]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
ailor Benjamin Morrell erroneously reports the existence of the island of New South Greenland near Antarctica.
"""

[[1823-03-19]]
lang = "en"
citation = "https://en.wikipedia.org/wiki/1823"
text = """
Emperor Agustín de Iturbide of Mexico abdicates, thus ending the short-lived First Mexican Empire.
"""

[[1823-03-19]]
lang = "es"
citation = "https://es.wikipedia.org/wiki/1823"
text = """
Agustín I abdica voluntariamente al trono de México.
"""
